#!/bin/bash

# onnx2rknn/docker.packages
# install packages and any other configs while build docker image.
# latest date: 2023.07.11
#
# written by Steve Jeong <steve@how2flow.net>

apt_options="-y --no-install-recommends"
ppa="ppa:deadsnakes/ppa"

apt-get update && apt-get install ${apt_options} \
  apt-utils \
  build-essential \
  curl \
  git \
  libgl1-mesa-glx \
  software-properties-common \
  sudo \
  tmux \
  unzip \
  vim \
  wget

add-apt-repository -y ${ppa}

apt-get update && apt-get install ${apt_options} \
  python3-pip \
  python3.8 \
  python3.8-dev \
  python3.8-venv \
  python3.9 \
  python3.9-dev \
  python3.9-venv


apt-get clean
