#!/bin/bash

# To set up a non-root user separately in docker image.
# latest date: 2023.03.07
#
# written by Steve Jeong <steve@how2flow.net>

id=$1
password="docker"

# set root password
echo "root:root" | chpasswd

# user account
groupadd --gid 1000 ${id} && \
  useradd --system --create-home --home-dir /home/${id} \
  --shell /bin/bash --gid ${id} --uid 1001 ${id}
# --password ${id}
# password option is just crypted in /etc/shadow.
# It is not applied to the actual.

# set user password
echo "$id:${password}" | chpasswd
