name: 'onnx2rknn v1.4.0 (CI/CD)'

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/Checkout@v3

      - name: 'Docker upload'
        uses: how2flow/upload-docker-action@v1
        with:
          context: ./docker/1.4.0
          repository: 'onnx2rknn'
          release: '1.4.0'
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
